### ISSUE TITLE
deviceDetector is undefined

### ISSUE THREAD

**Issue by gidmeister** [PoeHaH/devicedetector#1]
I followed the directions in this post.  First I included the script file:
 [script type="text/javascript" src="https://raw.githubusercontent.com/PoeHaH/devicedetector/master/devicedetector-min.js"](I'm using square brackets just for this message), and then I put in:
   if ((deviceDetector.device != 'tablet') && (deviceDetector.device != 'desktop'))

and that is where it failed.  It says "deviceDetector" is undefined.

**Comment by PoeHaH** [comment]
That's probably because you're trying to access the deviceDetector object before the script is fully loaded inside your page. I've adapted the README file to explain what you have to do. 

Basically, you have to wrap the code inside a document.ready handler. It can be done with jQuery or native javascript. Here's the jQuery way:

``` js
$(document).ready(function(){
   if ((deviceDetector.device != 'tablet') && (deviceDetector.device != 'desktop')){
      // Your code here that will execute when user is on a PHONE
   }
});
```

**Comment by PoeHaH** [comment]
Please let me know if this fixes your problem so I know if I can close the issue.
